=== iarriagada/GMP/gmp-epics-to-status/src/main/resources/edu/gemini/aspen/gmp/epicstostatus/gmp-epics-to-status-mapping.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema file defining the structure of the configuration file used by the gmp-epics-to-status module
            to map EPICS channels to GIAPI status items.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="Channels">
        <xs:annotation>
            <xs:documentation>
                The 'Channels' root element, can have any number of 'SimpleChannel', 'AlarmChannel' and
                'HealthChannel' child elements, in any order.
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element name="SimpleChannel" type="SimpleChannelType"/>
                <xs:element name="AlarmChannel" type="AlarmChannelType"/>
                <xs:element name="HealthChannel" type="HealthChannelType"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="SimpleChannelType">
        <xs:sequence>
            <xs:element name="statusitem" type="xs:string"/>
            <xs:element name="epicschannel" type="xs:string"/>
            <xs:element name="index" type="xs:unsignedShort" minOccurs="0" maxOccurs="1"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HealthChannelType">
        <xs:annotation>
            <xs:documentation>
                Type for health channels. The EPICS channel needs to be a DBR_String, and it will be published as
                a HealthStatusItem.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="SimpleChannelType"/>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="AlarmChannelType">
        <xs:annotation>
            <xs:documentation>
                Type for alarm channels. The configuration is the same as 'normal' channels.
            </xs:documentation>
        </xs:annotation>
        <xs:complexContent>
            <xs:extension base="SimpleChannelType"/>
        </xs:complexContent>
    </xs:complexType>
</xs:schema>

=== iarriagada/GMP/gmp-epics-to-status/src/test/resources/edu/gemini/aspen/gmp/epicstostatus/gmp-epics-to-status-mapping.xml
<?xml version="1.0"?>
<Channels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:noNamespaceSchemaLocation="gmp-epics-to-status-mapping.xsd">
    <SimpleChannel>
        <statusitem>giapitest:statusitemint</statusitem>
        <epicschannel>giapitest:epicschannelint</epicschannel>
        <index>0</index>
    </SimpleChannel>
    <AlarmChannel>
        <statusitem>giapitest:giapialarmfloat</statusitem>
        <epicschannel>giapitest:epicsalarmfloat</epicschannel>
    </AlarmChannel>
    <HealthChannel>
        <statusitem>giapitest:giapihealth1</statusitem>
        <epicschannel>giapitest:epicshealth1</epicschannel>
    </HealthChannel>

</Channels>
