=== iarriagada/GMP/gmp-commands-records/src/main/resources/edu/gemini/gmp/commands/records/giapi-apply-config.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:annotation>
        <xs:documentation>
            Schema file defining the structure of the configuration file used by the gmp-epics-status-service
            to create epics channels and map them to GIAPI status items.
        </xs:documentation>
    </xs:annotation>
    <xs:element name="Records">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Apply" type="ApplyType" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="ApplyType">
        <xs:sequence minOccurs="1">
            <xs:choice maxOccurs="unbounded">
                <xs:element name="SequenceCommand" type="SequenceCommandType" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="ConfigRecord" type="ConfigRecordType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:choice>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="timeout" type="xs:long" use="required"/>
    </xs:complexType>


    <xs:complexType name="ConfigRecordType">
        <xs:sequence>
            <xs:element name="ConfigSet" type="ConfigSetType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="ConfigSetType">
        <xs:sequence>
            <xs:element name="field" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:simpleType name="SequenceCommandType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="TEST"/>
            <xs:enumeration value="REBOOT"/>
            <xs:enumeration value="INIT"/>
            <xs:enumeration value="DATUM"/>
            <xs:enumeration value="PARK"/>
            <xs:enumeration value="VERIFY"/>
            <xs:enumeration value="END_VERIFY"/>
            <xs:enumeration value="GUIDE"/>
            <xs:enumeration value="END_GUIDE"/>
            <xs:enumeration value="OBSERVE"/>
            <xs:enumeration value="END_OBSERVE"/>
            <xs:enumeration value="PAUSE"/>
            <xs:enumeration value="CONTINUE"/>
            <xs:enumeration value="STOP"/>
            <xs:enumeration value="ABORT"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== iarriagada/GMP/src/main/config/giapi-apply-config.xml
<?xml version="1.0"?>
<Records xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="giapi-apply-config.xsd">
    <Apply name="apply" timeout="1000">
        <SequenceCommand>TEST</SequenceCommand>
        <SequenceCommand>REBOOT</SequenceCommand>
        <SequenceCommand>INIT</SequenceCommand>
        <SequenceCommand>DATUM</SequenceCommand>
        <SequenceCommand>PARK</SequenceCommand>
        <SequenceCommand>VERIFY</SequenceCommand>
        <SequenceCommand>END_VERIFY</SequenceCommand>
        <SequenceCommand>OBSERVE</SequenceCommand>
        <SequenceCommand>END_OBSERVE</SequenceCommand>
        <SequenceCommand>PAUSE</SequenceCommand>
        <SequenceCommand>CONTINUE</SequenceCommand>
        <SequenceCommand>STOP</SequenceCommand>
        <SequenceCommand>ABORT</SequenceCommand>
    </Apply>

    <Apply name="ao:apply" timeout="1000">
        <ConfigRecord name="ao:config">
            <ConfigSet name="configAo">
                <field>useAo</field>
                <field>magnitudeI</field>
                <field>r0</field>
                <field>optimize</field>
                <field>useLastVals</field>
            </ConfigSet>
            <ConfigSet name="configCal">
                <field>useCal</field>
                <field>magnitudeH</field>
            </ConfigSet>
        </ConfigRecord>
        <SequenceCommand>GUIDE</SequenceCommand>
        <SequenceCommand>END_GUIDE</SequenceCommand>
    </Apply>

    <Apply name="inst:apply" timeout="1000">
        <ConfigRecord name="inst:config">
            <ConfigSet name="configIfs">
                <field>integrationTime</field>
                <field>readoutMode</field>
                <field>numReads</field>
                <field>numCoadds</field>
                <field>startx</field>
                <field>starty</field>
                <field>endx</field>
                <field>endy</field>
            </ConfigSet>

            <ConfigSet name="configFOVIfsOffset">
                <field>xTarget</field>
                <field>yTarget</field>
            </ConfigSet>

            <ConfigSet name="configPolarizer">
                <field>deploy</field>
                <field>angle</field>
            </ConfigSet>

            <ConfigSet name="observationMode">
                <field>modeName</field>
            </ConfigSet>

            <ConfigSet name="selectAdc">
                <field>deploy</field>
                <field>overrideCas</field>
                <field>overrideZen</field>
                <field>orientation</field>
                <field>power</field>
            </ConfigSet>

            <ConfigSet name="selectPupilCamera">
                <field>deploy</field>
            </ConfigSet>

            <ConfigSet name="selectSource">
                <field>sourceIr</field>
                <field>sourceVis</field>
                <field>powerSC</field>
                <field>attenuationSC</field>
            </ConfigSet>

            <ConfigSet name="selectShutter">
                <field>entranceShutter</field>
                <field>calExitShutter</field>
                <field>calEntranceShutter</field>
                <field>calReferenceShutter</field>
                <field>calScienceShutter</field>
            </ConfigSet>

            <ConfigSet name="takeExposure">
                <field>selection</field>
                <field>intTime</field>
                <field>filename</field>
            </ConfigSet>
            <!--Apply Sequence Command Calibration Sets -->

            <ConfigSet name="cal:acquireWhiteFringe">
                <field>mark</field>
            </ConfigSet>

            <ConfigSet name="calToAoAlign">
                <field>phase</field>
            </ConfigSet>

            <ConfigSet name="centerPinhole">
                <field>mark</field>
            </ConfigSet>

            <ConfigSet name="ao:dmShape">
                <field>filename</field>
                <field>dmFlag</field>
            </ConfigSet>

            <ConfigSet name="ao:measureAOWFSCentroids">
                <field>mark</field>
            </ConfigSet>

            <ConfigSet name="cal:measureCalCentroids">
                <field>mark</field>
            </ConfigSet>

            <ConfigSet name="cal:measureHowfsOffsets">
                <field>filename</field>
            </ConfigSet>

            <ConfigSet name="takeDark">
                <field>selection</field>
                <field>intTime</field>
                <field>filename</field>
            </ConfigSet>

            <ConfigSet name="takeFlat">
                <field>selection</field>
                <field>intTime</field>
                <field>filename</field>
            </ConfigSet>

            <ConfigSet name="cal:transMaps">
                <field>filename</field>
            </ConfigSet>
            <!--Apply Sequence Command Engineering Sets (Miscellaneous access functions)-->

            <ConfigSet name="configAoSpatialFilter">
                <field>mode</field>
                <field>target</field>
                <field>now</field>
            </ConfigSet>

            <ConfigSet name="configSteeringMirrors">
                <field>selection</field>
                <field>track</field>
                <field>tip</field>
                <field>tilt</field>
                <field>focus</field>
            </ConfigSet>

            <ConfigSet name="correct">
                <field>selection</field>
            </ConfigSet>

            <ConfigSet name="ifs:log">
                <field>temperatures</field>
                <field>filename</field>
                <field>rate</field>
            </ConfigSet>

            <ConfigSet name="ifs:selectIfsFilter">
                <field>maskStr</field>
            </ConfigSet>

            <ConfigSet name="selectFocalPlaneMask">
                <field>maskStr</field>
            </ConfigSet>

            <ConfigSet name="selectLyotMask">
                <field>maskStr</field>
            </ConfigSet>

            <ConfigSet name="selectPupilPlaneMask">
                <field>maskStr</field>
            </ConfigSet>

            <ConfigSet name="statistics">
                <field>statStat</field>
                <field>statName</field>
                <field>statSelected</field>
            </ConfigSet>

            <ConfigSet name="alignAndCalib">
                <field>part1</field>
            </ConfigSet>
        </ConfigRecord>
    </Apply>
</Records>
