=== iarriagada/GMP/gmp-status-translator/src/main/resources/edu/gemini/gmp/status/translator/status-translator.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="TranslateStatus">
        <xs:complexType>
            <xs:choice  minOccurs="0" maxOccurs="unbounded">
                <xs:element name="Status" type="StatusType"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="dataType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="INT"/>
            <xs:enumeration value="FLOAT"/>
            <xs:enumeration value="DOUBLE"/>
            <xs:enumeration value="STRING"/>
            <xs:enumeration value="HEALTH"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="StatusType">
        <xs:sequence  minOccurs="1">
            <xs:element name="Maps" type="MapList"/>
        </xs:sequence>
        <xs:attribute name="originalName" type="xs:string" use="required"/>
        <xs:attribute name="translatedName" type="xs:string" use="required"/>
        <xs:attribute name="originalType" type="dataType" use="required"/>
        <xs:attribute name="translatedType" type="dataType" use="required"/>
        <xs:attribute name="default" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="MapList">
        <xs:choice  minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Map" type="MapType"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="MapType">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== iarriagada/GMP/integration-tests/src/test/resources/conf/status-translator.xml
<?xml version="1.0"?>
<TranslateStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../../../../giapi-status-translator/src/main/resources/statusservice/status-translator.xsd">
    <Status default="BAD" originalName="old" originalType="INT" translatedName="new"
            translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
</TranslateStatus>

=== iarriagada/GMP/src/main/config/status-translator.xml
<?xml version="1.0"?>
<TranslateStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../../giapi-status-service/src/main/resources/status-translator.xsd">
    <Status default="UNKNOWN" originalName="ifsFilter" originalType="STRING" translatedName="ifsFilter.gemini"
            translatedType="STRING">
        <Maps>
            <Map>
                <from>Y</from>
                <to>IFSFILT_Y_G1211</to>
            </Map>
            <Map>
                <from>J</from>
                <to>IFSFILT_J_G1212</to>
            </Map>
            <Map>
                <from>H</from>
                <to>IFSFILT_H_G1213</to>
            </Map>
            <Map>
                <from>K1</from>
                <to>IFSFILT_K1_G1214</to>
            </Map>
            <Map>
                <from>K2</from>
                <to>IFSFILT_K2_G1215</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
    <Status default="UNKNOWN" originalName="aoWfsFilter" originalType="STRING" translatedName="aoWfsFilter.gemini"
            translatedType="STRING">
        <Maps>
            <Map>
                <from>600NM_LOW_CUTOFF</from>
                <to>AOFILT_600NM_G1221</to>
            </Map>
            <Map>
                <from>700NM_LOW_CUTOFF</from>
                <to>AOFILT_700NM_G1222</to>
            </Map>
            <Map>
                <from>800NM_LOW_CUTOFF</from>
                <to>AOFILT_800NM_G1223</to>
            </Map>
            <Map>
                <from>900NM_LOW_CUTOFF</from>
                <to>AOFILT_900NM_G1224</to>
            </Map>
            <Map>
                <from>910_900NM_BAND_PASS</from>
                <to>AOFILT_910_900NM_BAND_PASS_G1225</to>
            </Map>
            <Map>
                <from>OPEN</from>
                <to>AOFILT_OPEN_G1226</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
    <Status default="UNKNOWN" originalName="ppmMask" originalType="STRING" translatedName="ppmMask.gemini"
            translatedType="STRING">
        <Maps>
            <Map>
                <from>CLEAR</from>
                <to>APOD_CLEAR_G6201</to>
            </Map>
            <Map>
                <from>CLEARGP</from>
                <to>APOD_CLEARGP_G6202</to>
            </Map>
            <Map>
                <from>APOD_Y</from>
                <to>APOD_Y_G6203</to>
            </Map>
            <Map>
                <from>APOD_J</from>
                <to>APOD_J_G6204</to>
            </Map>
            <Map>
                <from>APOD_H</from>
                <to>APOD_H_G6205</to>
            </Map>
            <Map>
                <from>APOD_K1</from>
                <to>APOD_K1_G6206</to>
            </Map>
            <Map>
                <from>APOD_K2</from>
                <to>APOD_K2_G6207</to>
            </Map>
            <Map>
                <from>NRM</from>
                <to>APOD_NRM_G6208</to>
            </Map>
            <Map>
                <from>APOD_HL</from>
                <to>APOD_HL_G6209</to>
            </Map>
            <Map>
                <from>APOD_star</from>
                <to>APOD_HSTAR_G6210</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
    <Status default="UNKNOWN" originalName="lyotMask" originalType="STRING" translatedName="lyotMask.gemini"
            translatedType="STRING">
        <Maps>
            <Map>
                <from>Blank</from>
                <to>LYOT_BLANK_G6232</to>
            </Map>
            <Map>
                <from>Open</from>
                <to>LYOT_OPEN_G6231</to>
            </Map>
            <Map>
                <from>Lyot_080_02</from>
                <to>LYOT_080_02_G6233</to>
            </Map>
            <Map>
                <from>Lyot_080_03</from>
                <to>LYOT_080_03_G6234</to>
            </Map>
            <Map>
                <from>Lyot_080_04</from>
                <to>LYOT_080_04_G6235</to>
            </Map>
            <Map>
                <from>Lyot_080_06</from>
                <to>LYOT_080_06_G6236</to>
            </Map>
            <Map>
                <from>Lyot_080_06_mirrored</from>
                <to>LYOT_080_06_MIRRORED_G6237</to>
            </Map>
            <Map>
                <from>Lyot_080_07</from>
                <to>LYOT_080_07_G6238</to>
            </Map>
            <Map>
                <from>Lyot_080_10</from>
                <to>LYOT_080_10_G6239</to>
            </Map>
            <Map>
                <from>Lyot_080_04_43</from>
                <to>LYOT_080_04_43_G6240</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
    <Status default="UNKNOWN" originalName="fpmMask" originalType="STRING" translatedName="fpmMask.gemini"
            translatedType="STRING">
        <Maps>
            <Map>
                <from>Open</from>
                <to>FPM_OPEN_G6221</to>
            </Map>
            <Map>
                <from>50umPIN</from>
                <to>FPM_PINHOLE_G6222</to>
            </Map>
            <Map>
                <from>WITH_DOT</from>
                <to>FPM_WITH_DOT_G6228</to>
            </Map>
            <Map>
                <from>SCIENCE</from>
                <to>FPM_SCIENCE_G6227</to>
            </Map>
            <Map>
                <from>FPM_K1</from>
                <to>FPM_K1_G6226</to>
            </Map>
            <Map>
                <from>FPM_H</from>
                <to>FPM_H_G6225</to>
            </Map>
            <Map>
                <from>FPM_J</from>
                <to>FPM_J_G6224</to>
            </Map>
            <Map>
                <from>FPM_Y</from>
                <to>FPM_Y_G6223</to>
            </Map>
            <Map>
                <from>UNKNOWN</from>
                <to>UNKNOWN</to>
            </Map>
        </Maps>
    </Status>
</TranslateStatus>

=== iarriagada/GMP/gmp-status-translator/src/test/resources/edu/gemini/gmp/status/translator/status-translator.xml
<?xml version="1.0"?>
<TranslateStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="../../../../../../../main/resources/edu/gemini/gmp/status/translator/status-translator.xsd">
    <Status default="BAD" originalName="old" originalType="INT" translatedName="new" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="oldnodefault" originalType="INT" translatedName="newnodefault" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="twice" originalType="INT" translatedName="first" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="twice" originalType="INT" translatedName="second" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="original1" originalType="INT" translatedName="target" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>0</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>2</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="original2" originalType="INT" translatedName="target" translatedType="HEALTH">
        <Maps>
            <Map>
                <from>2</from>
                <to>GOOD</to>
            </Map>
            <Map>
                <from>1</from>
                <to>WARNING</to>
            </Map>
            <Map>
                <from>0</from>
                <to>BAD</to>
            </Map>
        </Maps>
    </Status>
    <Status originalName="str" originalType="STRING" translatedName="target" translatedType="STRING" default="UNKNOWN">
        <Maps>
            <Map>
                <from>A</from>
                <to>B</to>
            </Map>
            <Map>
                <from>C</from>
                <to>D</to>
            </Map>
            <Map>
                <from>E</from>
                <to>F</to>
            </Map>
        </Maps>
    </Status>
</TranslateStatus>
